# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Andre Sander
description:         Andre Sander, Web Development, Angular, Single Page Application, NodeJS
baseurl:             /
paginate:            6
url:                 http://andresander.com

# Social
name: Andre Sander
mail: blog@andresander.com
twitter: _andresander
facebook: Sanderand
linkedin: profile/view?id=293081683
skype: andresanderandre
xing: profile/Andre_Sander15
medium: andresander

# Custom vars
version:             1.0.0
