# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Andre Sander
tagline:             Vom Working Holiday und Reisen
description:         Andre Sander's Blog über mein Work and Travel in Australien und alle Abenteuer auf meiner Reise
baseurl:             /
paginate:            6
url:                 http://blog.andresander.com

# Social
name: Andre Sander
mail: blog@andresander.com
twitter: _andresander
facebook: Sanderand
linkedin: profile/view?id=293081683
skype: andresanderandre
xing: profile/Andre_Sander15

# Custom vars
version:             1.0.0
